blank_issues_enabled: false
contact_links:
  - name: ğŸš€ í”„ë¡œì íŠ¸ ë³´ë“œ
    url: https://github.com/orgs/jiu-jitsu-org/projects/1
    about: ì „ì²´ í”„ë¡œì íŠ¸ ì§„í–‰ ìƒí™©ì„ í™•ì¸í•˜ì„¸ìš”
  - name: ğŸ‘¾ íŒ€ ë””ìŠ¤ì½”ë“œ
    url: https://discord.com/channels/1349967166652289094/1349967167453659212
    about: ë¹ ë¥¸ ì§ˆë¬¸ì´ë‚˜ ë…¼ì˜ëŠ” ë””ìŠ¤ì½”ë“œì—ì„œ
